//! Shell-integration bootstrap: the rc files LoganTerminal generates and
//! injects so a spawned shell reports its cwd (OSC 7) and its prompt/command
//! lifecycle (OSC 133 A/B/C/D) — the signals behind the branch chip, the
//! prompt-jump shortcuts, exit-code and duration chips, and long-command
//! notifications.
//!
//! Both rc scripts also emulate the *login* startup sequence, because a
//! GUI-launched .app inherits a minimal PATH and the fix-ups (path_helper,
//! Homebrew) live in files only a login shell reads. The tests at the bottom
//! run real zsh/bash to prove that chaining still works and never
//! double-sources the user's config.

/// Base name of a shell path, lowercased, `.exe` stripped — "zsh", "bash",
/// "powershell", ... Used to pick which shell-integration hooks to inject.
/// Exact-match comparisons on the result mean e.g. a shell named "notzsh"
/// gets none (an `ends_with("zsh")` check would have matched it).
pub fn shell_base_name(path: &str) -> String {
    let base = path.rsplit(['/', '\\']).next().unwrap_or(path);
    let base = base.to_ascii_lowercase();
    base.strip_suffix(".exe").map(str::to_owned).unwrap_or(base)
}

/// Directory holding every generated rc file, under the user's home.
fn hook_dir() -> anyhow::Result<std::path::PathBuf> {
    let home = std::env::var("HOME")?;
    Ok(std::path::PathBuf::from(&home)
        .join(".logan-terminal")
        .join("shell"))
}

/// Set up a ZDOTDIR that emits OSC 7 and OSC 133 from zsh's precmd/preexec
/// hooks. Returns the ZDOTDIR path to inject into the environment.
pub fn ensure_zsh_hook_dir() -> anyhow::Result<String> {
    let dir = hook_dir()?;
    write_zsh_hook_files(&dir)?;
    Ok(dir.to_string_lossy().into_owned())
}

/// Writes the hook `.zshrc` plus chain stubs for every other zsh startup
/// file. Setting ZDOTDIR redirects zsh away from $HOME for *all* of them,
/// so without the stubs a login shell would skip the user's ~/.zprofile —
/// exactly the file that holds PATH setup (Homebrew) on a typical macOS
/// machine.
pub fn write_zsh_hook_files(dir: &std::path::Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(dir)?;
    for name in [".zshenv", ".zprofile", ".zlogin"] {
        std::fs::write(dir.join(name), zsh_chain_stub(name))?;
    }
    std::fs::write(dir.join(".zshrc"), ZSH_RC)?;
    Ok(())
}

/// A ZDOTDIR stub that just runs the user's real counterpart, with ZDOTDIR
/// pointing at $HOME for its duration (zsh scopes that assignment to the
/// `source` builtin) so anything it sources relative to ZDOTDIR resolves.
fn zsh_chain_stub(name: &str) -> String {
    format!(
        r#"# Auto-generated by LoganTerminal — do not edit.
if [[ -r "$HOME/{name}" ]]; then
  ZDOTDIR="$HOME" source "$HOME/{name}"
fi
"#
    )
}

/// Write the bash rc file that mirrors [`ZSH_RC`]'s OSC 7/133 integration
/// and return its path, to be passed to bash via `--rcfile`.
#[cfg(unix)]
pub fn ensure_bash_hook_file() -> anyhow::Result<String> {
    let dir = hook_dir()?;
    std::fs::create_dir_all(&dir)?;
    let rc = dir.join("bashrc");
    std::fs::write(&rc, BASH_RC)?;
    Ok(rc.to_string_lossy().into_owned())
}

/// The zsh hook rc, kept as a real shell file so it stays editable (and
/// syntax-highlighted) instead of hiding inside a Rust string literal.
const ZSH_RC: &str = include_str!("shell/logan.zsh");

/// Bash counterpart of [`ZSH_RC`]; see `shell/logan.bash`.
#[cfg(unix)]
const BASH_RC: &str = include_str!("shell/logan.bash");

#[cfg(test)]
mod tests {
    use super::*;

    /// Every OSC marker the frontend consumes, as a fixture — an rc edit that
    /// silently drops one would otherwise only show up as a dead feature.
    const REQUIRED_MARKERS: [&str; 5] = ["]133;A", "]133;B", "]133;C", "]133;D", "]7;file://"];

    #[test]
    fn shell_base_name_variants() {
        assert_eq!(shell_base_name("/bin/zsh"), "zsh");
        assert_eq!(shell_base_name("/opt/homebrew/bin/bash"), "bash");
        assert_eq!(shell_base_name("bash"), "bash");
        assert_eq!(
            shell_base_name(r"C:\Program Files\Git\bin\bash.exe"),
            "bash"
        );
        assert_eq!(
            shell_base_name(r"C:\WINDOWS\System32\PowerShell.EXE"),
            "powershell"
        );
        // Exact match wanted: a shell that merely *ends* in "zsh" is not zsh.
        assert_eq!(shell_base_name("/usr/local/bin/notzsh"), "notzsh");
    }

    #[test]
    fn zsh_rc_covers_all_osc_markers() {
        for marker in REQUIRED_MARKERS {
            assert!(ZSH_RC.contains(marker), "zsh rc lost marker {marker}");
        }
    }

    #[test]
    #[cfg(unix)]
    fn bash_rc_covers_all_osc_markers() {
        for marker in REQUIRED_MARKERS {
            assert!(BASH_RC.contains(marker), "bash rc lost marker {marker}");
        }
    }

    /// Runs the generated rc file in a real interactive bash (present on
    /// every unix dev/CI machine) and checks the sequences it emits. The C
    /// marker is deliberately not asserted — it needs PS0 (bash >= 4.4) and
    /// macOS ships 3.2.
    #[test]
    #[cfg(unix)]
    fn bash_rc_emits_markers_in_a_real_bash() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let dir = std::env::temp_dir().join(format!("logan-bashrc-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join("bashrc");
        std::fs::write(&rc, BASH_RC).unwrap();

        let mut child = Command::new("bash")
            .arg("--rcfile")
            .arg(&rc)
            .arg("-i")
            // Point HOME at the empty temp dir so no user .bashrc interferes.
            .env("HOME", &dir)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash should be available on unix");
        child
            .stdin
            .as_mut()
            .unwrap()
            // The B marker lives inside PS1 and only reaches the output
            // through readline's prompt redisplay — which GitHub's macOS
            // runners render via the horizontal-scroll fallback that never
            // writes the PS1 tail to a pipe (same bash 3.2 writes it fine
            // locally; found when this test first ran in CI, 2026-07-05).
            // So B is asserted at the source instead: the shell checks the
            // PS1 it actually carries and echoes a sentinel.
            .write_all(b"case \"$PS1\" in *\"]133;B\"*) echo PS1-CARRIES-B;; esac\nfalse\nexit\n")
            .unwrap();
        let all = combined_output(child);

        assert!(
            all.contains("\x1b]133;A\x07"),
            "prompt marker missing: {all:?}"
        );
        assert!(
            all.contains("\x1b]133;D;1\x07"),
            "exit-code marker for `false` missing: {all:?}"
        );
        assert!(
            all.contains("\x1b]133;D;0\x07"),
            "startup D;0 missing: {all:?}"
        );
        assert!(all.contains("\x1b]7;file://"), "osc7 cwd missing: {all:?}");
        assert!(
            all.contains("PS1-CARRIES-B"),
            "PS1 lacks the 133;B input marker: {all:?}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// stdout and stderr as one string — the markers under test may land on
    /// either, depending on how the shell renders its prompt.
    #[cfg(unix)]
    fn combined_output(child: std::process::Child) -> String {
        let out = child.wait_with_output().unwrap();
        format!(
            "{}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        )
    }

    /// Real interactive zsh in a cwd that needs encoding (space, literal
    /// '%', multibyte) — the emitted OSC 7 must be byte-wise
    /// percent-encoded so the frontend decode can't mangle it.
    #[test]
    #[cfg(unix)]
    fn zsh_rc_percent_encodes_osc7_pwd() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let base = std::env::temp_dir().join(format!("logan-zsh-enc-test-{}", std::process::id()));
        let home = base.join("home");
        let weird = home.join("we ird%40中");
        std::fs::create_dir_all(&weird).unwrap();
        let zdot = base.join("zdot");
        write_zsh_hook_files(&zdot).unwrap();

        let mut child = match Command::new("zsh")
            .arg("-i")
            .env("HOME", &home)
            .env("ZDOTDIR", &zdot)
            .current_dir(&weird)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
        {
            Ok(c) => c,
            Err(_) => {
                // No zsh on this machine — nothing to test.
                let _ = std::fs::remove_dir_all(&base);
                return;
            }
        };
        child.stdin.as_mut().unwrap().write_all(b"exit\n").unwrap();
        let all = combined_output(child);
        assert!(
            all.contains("we%20ird%2540%E4%B8%AD"),
            "encoded cwd missing from OSC 7: {all:?}"
        );

        let _ = std::fs::remove_dir_all(&base);
    }

    /// Same encoding check for the bash rc (LC_ALL=C byte-wise loop, which
    /// must also hold on macOS's bash 3.2).
    #[test]
    #[cfg(unix)]
    fn bash_rc_percent_encodes_osc7_pwd() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let dir = std::env::temp_dir().join(format!("logan-bash-enc-test-{}", std::process::id()));
        let weird = dir.join("we ird%40中");
        std::fs::create_dir_all(&weird).unwrap();
        let rc = dir.join("bashrc");
        std::fs::write(&rc, BASH_RC).unwrap();

        let mut child = Command::new("bash")
            .arg("--rcfile")
            .arg(&rc)
            .arg("-i")
            .env("HOME", &dir)
            .current_dir(&weird)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash should be available on unix");
        child.stdin.as_mut().unwrap().write_all(b"exit\n").unwrap();
        let all = combined_output(child);
        assert!(
            all.contains("we%20ird%2540%E4%B8%AD"),
            "encoded cwd missing from OSC 7: {all:?}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn zsh_hook_dir_chains_every_user_startup_file() {
        let dir = std::env::temp_dir().join(format!("logan-zdot-test-{}", std::process::id()));
        write_zsh_hook_files(&dir).unwrap();

        for name in [".zshenv", ".zprofile", ".zlogin"] {
            let content = std::fs::read_to_string(dir.join(name)).unwrap();
            assert!(
                content.contains(&format!("source \"$HOME/{name}\"")),
                "{name} stub does not chain the user's file: {content:?}"
            );
        }
        let zshrc = std::fs::read_to_string(dir.join(".zshrc")).unwrap();
        assert_eq!(zshrc, ZSH_RC);

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// End-to-end check of the login-shell PATH fix: a zsh started the way
    /// the app starts it (-l, hook ZDOTDIR, minimal env) must pick up PATH
    /// additions from ~/.zprofile via the chain stub — that's where
    /// Homebrew lives on a typical macOS machine, and a Dock-launched .app
    /// otherwise gets no PATH beyond the system defaults.
    #[test]
    #[cfg(unix)]
    fn login_zsh_reads_user_zprofile_through_hook_dir() {
        use std::process::Command;

        let base = std::env::temp_dir().join(format!("logan-zlogin-test-{}", std::process::id()));
        let home = base.join("home");
        let zdot = base.join("zdot");
        std::fs::create_dir_all(&home).unwrap();
        write_zsh_hook_files(&zdot).unwrap();
        std::fs::write(
            home.join(".zprofile"),
            "export PATH=\"$PATH:/logan-zprofile-sentinel\"\n",
        )
        .unwrap();

        let out = match Command::new("zsh")
            .args(["-l", "-c", "print -r -- $PATH"])
            .env_clear()
            .env("HOME", &home)
            .env("PATH", "/usr/bin:/bin")
            .env("ZDOTDIR", &zdot)
            .output()
        {
            Ok(out) => out,
            Err(_) => {
                // No zsh on this machine (minimal CI image) — nothing to test.
                let _ = std::fs::remove_dir_all(&base);
                return;
            }
        };
        let path = String::from_utf8_lossy(&out.stdout);
        assert!(
            path.contains("/logan-zprofile-sentinel"),
            "login zsh did not source the chained ~/.zprofile: {path:?}"
        );

        let _ = std::fs::remove_dir_all(&base);
    }

    /// The rc's login emulation must read the profile file (that's where
    /// PATH setup lives) and must not double-source ~/.bashrc when the
    /// profile already chains it — the standard macOS bash arrangement.
    #[test]
    #[cfg(unix)]
    fn bash_rc_sources_profile_and_bashrc_exactly_once() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let dir =
            std::env::temp_dir().join(format!("logan-bash-profile-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join("bashrc");
        std::fs::write(&rc, BASH_RC).unwrap();
        std::fs::write(
            dir.join(".bash_profile"),
            "export PATH=\"$PATH:/logan-bash-profile-sentinel\"\n\
             [ -r \"$HOME/.bashrc\" ] && . \"$HOME/.bashrc\"\n",
        )
        .unwrap();
        std::fs::write(
            dir.join(".bashrc"),
            "LOGAN_BASHRC_COUNT=$((${LOGAN_BASHRC_COUNT:-0}+1))\n",
        )
        .unwrap();

        let mut child = Command::new("bash")
            .arg("--rcfile")
            .arg(&rc)
            .arg("-i")
            .env("HOME", &dir)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash should be available on unix");
        child
            .stdin
            .as_mut()
            .unwrap()
            .write_all(b"echo \"PATH=$PATH RC_COUNT=$LOGAN_BASHRC_COUNT\"\nexit\n")
            .unwrap();
        let all = combined_output(child);

        assert!(
            all.contains("/logan-bash-profile-sentinel"),
            "profile PATH addition missing: {all:?}"
        );
        assert!(
            all.contains("RC_COUNT=1"),
            "bashrc should run exactly once (via the profile): {all:?}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Without any profile file the rc falls back to sourcing ~/.bashrc
    /// directly, preserving the pre-login-emulation behavior.
    #[test]
    #[cfg(unix)]
    fn bash_rc_falls_back_to_bashrc_without_profile() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let dir =
            std::env::temp_dir().join(format!("logan-bash-rconly-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let rc = dir.join("bashrc");
        std::fs::write(&rc, BASH_RC).unwrap();
        std::fs::write(
            dir.join(".bashrc"),
            "LOGAN_BASHRC_COUNT=$((${LOGAN_BASHRC_COUNT:-0}+1))\n",
        )
        .unwrap();

        let mut child = Command::new("bash")
            .arg("--rcfile")
            .arg(&rc)
            .arg("-i")
            .env("HOME", &dir)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("bash should be available on unix");
        child
            .stdin
            .as_mut()
            .unwrap()
            .write_all(b"echo \"RC_COUNT=$LOGAN_BASHRC_COUNT\"\nexit\n")
            .unwrap();
        let all = combined_output(child);

        assert!(
            all.contains("RC_COUNT=1"),
            "fallback ~/.bashrc sourcing missing or doubled: {all:?}"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }
}
