# Auto-generated by LoganTerminal — do not edit.
# Chain the user's zshrc first so we don't shadow their config.
if [[ -r "$HOME/.zshrc" ]]; then
  ZDOTDIR="$HOME" source "$HOME/.zshrc"
fi

# Runs FIRST among precmd hooks so $? still reflects the command that just
# finished, before any other precmd hook (theme, framework, ...) gets a
# chance to run something that clobbers it.
_logan_terminal_precmd_early() {
  printf '\e]133;D;%d\a' "$?"
}

# Percent-encode $PWD byte-wise for the file:// URL — a directory literally
# named like "foo%20bar" must not decode into something else. nomultibyte
# makes subscripts/lengths byte-based so UTF-8 names encode per byte.
_logan_terminal_emit_osc7() {
  setopt localoptions nomultibyte
  local host="${HOST:-${HOSTNAME:-localhost}}" str="$PWD" out="" i ch
  for (( i = 1; i <= ${#str}; i++ )); do
    ch="${str[$i]}"
    if [[ "$ch" == [A-Za-z0-9/_.~-] ]]; then
      out+="$ch"
    else
      # "'c" may sign-extend high bytes on some shells; mask to one byte.
      printf -v ch '%d' "'$ch"
      printf -v ch '%%%02X' "$(( ch & 0xFF ))"
      out+="$ch"
    fi
  done
  printf '\e]7;file://%s%s\a' "$host" "$out"
}

# Runs LAST so it sees the final PROMPT after theme/framework precmd hooks
# (oh-my-zsh, powerlevel10k, ...) have finished rebuilding it.
_logan_terminal_precmd_late() {
  _logan_terminal_emit_osc7
  printf '\e]133;A\a'
  # Zero-width marker (%{...%}) so it isn't counted as visible width by
  # zle; idempotent so frameworks that redraw PROMPT unchanged don't grow
  # it every prompt.
  if [[ "$PROMPT" != *$'\e]133;B'* ]]; then
    PROMPT="${PROMPT}"'%{'$'\e]133;B\a''%}'
  fi
}

_logan_terminal_preexec() {
  printf '\e]133;C\a'
}

precmd_functions=(_logan_terminal_precmd_early "${precmd_functions[@]}")
precmd_functions+=(_logan_terminal_precmd_late)

if [[ -n "${preexec_functions+set}" ]]; then
  preexec_functions+=(_logan_terminal_preexec)
else
  preexec_functions=(_logan_terminal_preexec)
fi

# Emit once on startup so consumers get an initial cwd and prompt marker.
_logan_terminal_precmd_early
_logan_terminal_precmd_late
