# Auto-generated by LoganTerminal — do not edit.
# bash reads this via --rcfile, which replaces every startup file bash would
# read on its own — and a login (-l) bash would ignore --rcfile entirely. So
# emulate the full login + interactive sequence here: a GUI-launched app
# starts with a minimal PATH, and the fix-ups live in /etc/profile
# (path_helper) and the user's profile file (Homebrew et al).
[[ $- == *i* ]] || return
[[ -r /etc/profile ]] && source /etc/profile
# First existing profile file wins — the same rule login bash applies. A
# profile normally sources ~/.bashrc itself; only when none exists fall back
# to the plain rc chain, so nothing runs twice.
_logan_terminal_profile=
for _logan_terminal_f in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
  if [[ -r "$_logan_terminal_f" ]]; then
    _logan_terminal_profile="$_logan_terminal_f"
    break
  fi
done
if [[ -n "$_logan_terminal_profile" ]]; then
  source "$_logan_terminal_profile"
else
  [[ -r /etc/bash.bashrc ]] && source /etc/bash.bashrc
  [[ -r "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
fi
unset _logan_terminal_profile _logan_terminal_f

# Runs FIRST in PROMPT_COMMAND so $? still reflects the command that just
# finished; `return`s that status so the user's own PROMPT_COMMAND (spliced
# right after us) still sees the real exit code in $?.
_logan_terminal_precmd_early() {
  _LOGAN_TERMINAL_STATUS=$?
  printf '\e]133;D;%d\a' "$_LOGAN_TERMINAL_STATUS"
  return "$_LOGAN_TERMINAL_STATUS"
}

# Percent-encode $PWD byte-wise for the file:// URL — a directory literally
# named like "foo%20bar" must not decode into something else. LC_ALL=C makes
# ${str:i:1} byte-based so UTF-8 names encode per byte (works on bash 3.2).
_logan_terminal_emit_osc7() {
  local LC_ALL=C str="$PWD" out="" i ch
  for (( i = 0; i < ${#str}; i++ )); do
    ch="${str:i:1}"
    case "$ch" in
      [A-Za-z0-9/_.~-]) out+="$ch" ;;
      *)
        # bash 3.2's "'c" sign-extends high bytes to negative values —
        # mask to one byte before formatting.
        printf -v ch '%d' "'$ch"
        printf -v ch '%%%02X' "$(( ch & 0xFF ))"
        out+="$ch" ;;
    esac
  done
  printf '\e]7;file://%s%s\a' "${HOSTNAME:-localhost}" "$out"
}

# Runs LAST so it sees PS1 after the user's PROMPT_COMMAND (git prompts etc.)
# has finished rebuilding it.
_logan_terminal_precmd_late() {
  _logan_terminal_emit_osc7
  printf '\e]133;A\a'
  # \[...\] so readline gives it zero width; idempotent so PROMPT_COMMANDs
  # that rebuild PS1 unchanged don't grow it every prompt.
  if [[ "$PS1" != *']133;B'* ]]; then
    PS1="${PS1}\\[\\e]133;B\\a\\]"
  fi
}

if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == 'declare -a'* ]]; then
  PROMPT_COMMAND=(_logan_terminal_precmd_early "${PROMPT_COMMAND[@]}" _logan_terminal_precmd_late)
else
  _logan_terminal_user_pc="${PROMPT_COMMAND-}"
  while [[ "$_logan_terminal_user_pc" == *[';'$' \t\n'] ]]; do
    _logan_terminal_user_pc="${_logan_terminal_user_pc%?}"
  done
  PROMPT_COMMAND="_logan_terminal_precmd_early${_logan_terminal_user_pc:+; $_logan_terminal_user_pc}; _logan_terminal_precmd_late"
  unset _logan_terminal_user_pc
fi

# PS0 (bash >= 4.4) expands after a command is read, before it runs — the
# preexec moment. On older bash (macOS ships 3.2) it's an unused variable:
# the C marker simply never fires, everything else still works.
PS0="${PS0-}\\e]133;C\\a"

# Emit once on startup so consumers get an initial cwd and prompt marker.
_logan_terminal_precmd_early
_logan_terminal_precmd_late
